# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0002_auto_20161001_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ageee',
        ),
    ]
