# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0003_remove_profile_ageee'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activeToken',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='f', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='f', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='f', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(default='f', max_length=10),
        ),
    ]
