# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0013_post_last_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='comments',
        ),
    ]
